/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-GD.h
 #	source generated by 4D Plugin Wizard
 #	Project : GD
 #	author : miyako
 #	2020/06/20
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_GD_H
#define PLUGIN_GD_H

#include "4DPluginAPI.h"
#include "4DPlugin-JSON.h"

#include "gd.h"

#include "C_BLOB.h"

#pragma mark -

void GD_Filter(PA_PluginParameters params);
void GD_Animate(PA_PluginParameters params);
void GD_Rotate(PA_PluginParameters params);

#define gdLoopInfinite 0
#define CONVERT_PICTURE  (1002)
#define kcpRetainOnly 1

typedef enum {
    IMG_FILTER_NONE = 0,
    IMG_FILTER_NEGATE,
    IMG_FILTER_GRAYSCALE,
    IMG_FILTER_EDGEDETECT,
    IMG_FILTER_EMBOSS,
    IMG_FILTER_GAUSSIAN_BLUR,
    IMG_FILTER_SELECTIVE_BLUR,
    IMG_FILTER_MEAN_REMOVAL,
    IMG_FILTER_SMOOTH,
    IMG_FILTER_CONTRAST,
    IMG_FILTER_BRIGHTNESS,
    IMG_FILTER_SCATTER,
    IMG_FILTER_PIXELATE,
    IMG_FILTER_COLORIZE,
    IMG_FILTER_CONVOLUTION
}gd_filter_type_t;

#endif /* PLUGIN_GD_H */
